program_param:
  wandb_key: 27b98c412ec8a5a4e2a7433293569c9122e88fab
  project_name: jigsaw
  seed: 42

data_param:
  dir_name: jigsaw-toxic-severity-rating
  train_file_name: added_data.csv
  infer_file_name: comments_to_score.csv
  valid_file_name: toxic_task.csv
  do_score_check: True

model_param:
  model_name: roberta
  max_length: 128
  scheduler: cos_ann
  mix_precision: True
  num_classes: 1
  device: cuda

train_param:
  epochs: 4
  lr: 1e-4
  min_lr: 1e-6
  weight_decay: 1e-6
  num_folds: 5
  accumulate_grad_batches: 2
  ranking_margin: 0.5
  batch_size: 16
  T_max: 500
  T_0: 50
  save_dir: checkpoint/roberta
  loss: margin_ranking_loss
  num_workers: 2
  shuffle: True
  pin_memory: True
  drop_last: True

valid_param:
  batch_size: 64
  num_workers: 2
  shuffle: False
  pin_memory: True
  
infer_param:
  batch_size: 64
  num_workers: 2
  shuffle: False
  pin_memory: True
  checkpoint_path: checkpoint/roberta/roberta.bin
  save_dir: /jigsaw/output/roberta